name: DCO Sign-Off Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches:
      - main

jobs:
  dco:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DCO Check
        uses: actions/dco@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

