name: Check Signed-off-by

on:
  push:
    branches: [main]

jobs:
  check-signed-off-by:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for Signed-off-by
        run: |
          git log -1 --pretty="%s" | grep -q "Signed-off-by:" || exit 1
