name: DCO Check

on: [pull_request]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DCO Check
        uses: docker://ghcr.io/scality/dco-check:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

